/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Entity.EntPegawai;

/**
 *
 * @author BOAI
 */
public class FormHome extends javax.swing.JFrame {

    /**
     * Creates new form FormAccessories
     */
    public FormHome() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        BtnPegawai = new javax.swing.JButton();
        BtnPenjualan = new javax.swing.JButton();
        BtnAcc = new javax.swing.JButton();
        BtnLogout = new javax.swing.JButton();
        BtnDistributor = new javax.swing.JButton();
        BtnSup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel2.setText("\"Solusi Tepat Accesoris SmartPhone Kamu \"");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204), 5));

        BtnPegawai.setBackground(new java.awt.Color(255, 255, 255));
        BtnPegawai.setFont(new java.awt.Font("Old School United Stencil Itali", 0, 18)); // NOI18N
        BtnPegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/01 pegawai.png"))); // NOI18N
        BtnPegawai.setText("Pegawai");
        BtnPegawai.setActionCommand("BtnPegawai");
        BtnPegawai.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        BtnPegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnPegawaiMouseClicked(evt);
            }
        });
        BtnPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPegawaiActionPerformed(evt);
            }
        });

        BtnPenjualan.setBackground(new java.awt.Color(255, 255, 255));
        BtnPenjualan.setFont(new java.awt.Font("Old School United Stencil Itali", 0, 18)); // NOI18N
        BtnPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/05 penjualan.png"))); // NOI18N
        BtnPenjualan.setText("Penjualan");
        BtnPenjualan.setActionCommand("BtnPenjualan");
        BtnPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPenjualanActionPerformed(evt);
            }
        });

        BtnAcc.setBackground(new java.awt.Color(255, 255, 255));
        BtnAcc.setFont(new java.awt.Font("Old School United Stencil Itali", 0, 18)); // NOI18N
        BtnAcc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/02 aksesoris.png"))); // NOI18N
        BtnAcc.setText("Accessories");
        BtnAcc.setActionCommand("BtnAccessories");
        BtnAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAccActionPerformed(evt);
            }
        });

        BtnLogout.setBackground(new java.awt.Color(255, 255, 255));
        BtnLogout.setFont(new java.awt.Font("Old School United Stencil Itali", 0, 18)); // NOI18N
        BtnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/06 logout_1.png"))); // NOI18N
        BtnLogout.setText("Log Out");
        BtnLogout.setActionCommand("BtnLogOut");
        BtnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogoutActionPerformed(evt);
            }
        });

        BtnDistributor.setBackground(new java.awt.Color(255, 255, 255));
        BtnDistributor.setFont(new java.awt.Font("Old School United Stencil Itali", 0, 18)); // NOI18N
        BtnDistributor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/03 .1 distibutor.png"))); // NOI18N
        BtnDistributor.setText("Distributor");
        BtnDistributor.setActionCommand("BtnDistributor");
        BtnDistributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDistributorActionPerformed(evt);
            }
        });

        BtnSup.setBackground(new java.awt.Color(255, 255, 255));
        BtnSup.setFont(new java.awt.Font("Old School United Stencil Itali", 0, 18)); // NOI18N
        BtnSup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/07 cari.png"))); // NOI18N
        BtnSup.setText("supplier");
        BtnSup.setActionCommand("Btn_Caribarang");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnPegawai)
                        .addGap(18, 18, 18)
                        .addComponent(BtnAcc)
                        .addGap(26, 26, 26)
                        .addComponent(BtnDistributor))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnPenjualan)
                        .addGap(8, 8, 8)
                        .addComponent(BtnSup, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(BtnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(BtnPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtnAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnDistributor, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnSup, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2)))
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnPegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPegawaiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPegawaiMouseClicked

    private void BtnDistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDistributorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnDistributorActionPerformed

    private void BtnPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPegawaiActionPerformed
        FormPegawai FormPegawai = new FormPegawai();
        FormPegawai.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnPegawaiActionPerformed

    private void BtnAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAccActionPerformed
        FormAccessories formAccessories = new FormAccessories();
        formAccessories.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAccActionPerformed

    private void BtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogoutActionPerformed
        FormLogin formLogin = new FormLogin();
        formLogin.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnLogoutActionPerformed

    private void BtnPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPenjualanActionPerformed
        // TODO add your handling code here:
        FromPenjualan fromPenjualan = new FromPenjualan();
        fromPenjualan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnPenjualanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormHome().setVisible(true);
            }
        });
    }
//..
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAcc;
    private javax.swing.JButton BtnDistributor;
    private javax.swing.JButton BtnLogout;
    private javax.swing.JButton BtnPegawai;
    private javax.swing.JButton BtnPenjualan;
    private javax.swing.JButton BtnSup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
